name: test_sql
description: A sample command-line application.
version: 1.0.0
publish_to: "none"
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  daravel:
    git:
      url: https://github.com/Yoga3911/sql_conn.git


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
